### PR TITLE
add files for fz3b

### PR DESCRIPTION
**Pull request by changhai0109**
new file:   board_files/fz3b/A.0/board.xml
	new file:   board_files/fz3b/A.0/fz3a_board.jpeg
	new file:   board_files/fz3b/A.0/part0_pins.xml
	new file:   board_files/fz3b/A.0/preset.xml
	new file:   docs/FZ3B-Hardware-Handbook.pdf
	new file:   pynq/edgeboard-fz3b/base/base.bit
	new file:   pynq/edgeboard-fz3b/base/base.hwh
	new file:   pynq/edgeboard-fz3b/base/base.xsa
	new file:   pynq/edgeboard-fz3b/edgeboard-fz3b.spec
	new file:   pynq/edgeboard-fz3b/packages/boot_leds/boot.py
	new file:   pynq/edgeboard-fz3b/packages/boot_leds/pre.sh
	new file:   pynq/edgeboard-fz3b/petalinux_bsp/hardware_project/base.xsa
	new file:   pynq/edgeboard-fz3b/petalinux_bsp/meta-user/recipes-bsp/device-tree/files/system-user.dtsi

### CODE REVIEW

**Comment by zhutmost** [comment]
Have u tried your generated image? If it runs well, I will merge your pr. 

Thanks a lot. :D ~~~

**Comment by changhai0109** [comment]
Yes LOL, I have built the image, and seems well (at least I can control the GPIO led).

Before merging the pr, I am thinking about upload the image, after uploading the image I will ping you. 

Thanks!

**Comment by zhutmost** [comment]
I will update the README and add your username soon.

**Comment by changhai0109** [comment]
Already uploaded the image to aliyundrive
https://www.aliyundrive.com/s/J8SkxVZ6Mrw

Thanks!

**Pull request merged**
